apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: My-Company-Software
  description: Software catalogs .
  tags:
    - go
    - website
spec:
  type: service
  lifecycle: production
  owner: your-team
